/*
 * Copyright (C) 2026 Optim Enterprises BV
 *
 * This is free software, licensed under the BSD 3-Clause License.
 *
 * The in-kernel coarse filters for the FreeBSD capture path.
 *
 * ===================== WHY THIS FILE EXISTS, AND WHAT IT COST ==============
 *
 * There are TWO programs here and the difference between them is the central
 * lesson of this port. Both replace versions that shipped broken.
 *
 * 1. bpf_tls_clienthello -- recognises the START of a TLS ClientHello.
 *
 *    The first version used FIXED offsets: record type at byte 54 (14 Ethernet
 *    + 20 IPv4 + 20 TCP) and handshake type at 59. That is correct only when
 *    the TCP header carries no options. MEASURED on FreeBSD 16.0:
 *    `sysctl net.inet.tcp.rfc1323` is 1, so TCP timestamps are on by default,
 *    the TCP header is 32 bytes, and the record actually starts at 66. Byte 54
 *    was a TCP option byte. The program installed cleanly, reported no error,
 *    and never matched anything -- indistinguishable from "no interesting
 *    traffic", which is the worst possible failure mode.
 *
 *    This version walks the header lengths instead:
 *
 *        X = 4 * (byte[14] & 0x0f)      ; IP header length, with IP options
 *        A = byte[X + 26] & 0xf0        ; TCP data-offset byte
 *        X = (A >> 2) + 14 + X          ; TLS record base
 *
 *    correct for 20-, 32- and 40-byte TCP headers and for IP options, and it
 *    handles VLAN and QinQ tags, which the old version silently mis-parsed.
 *
 * 2. bpf_tcp_payload -- the DELIVERY filter, and the fix for a second bug.
 *
 *    Gating DELIVERY on the ClientHello pattern is wrong, because a
 *    ClientHello commonly spans TCP segments and a CONTINUATION segment does
 *    not begin with 0x16. MEASURED: OpenSSL 3.5 sends a 1545-byte ClientHello
 *    (ML-KEM hybrid key shares), the first segment carries 1448 bytes, and the
 *    remainder arrives in a second segment which the pattern filter dropped.
 *    The userspace reassembler therefore reported "need more bytes" forever and
 *    no hostname was ever produced, while the counters showed a healthy
 *    matcher. With modern crypto this is the COMMON case, not an edge case.
 *
 *    So delivery is gated on "IPv4 + TCP + not a fragment + non-empty
 *    payload", and the precise per-flow decision belongs to the reassembler
 *    working on the completed stream. bpf_tls_clienthello still runs, as the
 *    cheap in-kernel classifier and for counters.
 *
 * ============================ HOW THIS IS VERIFIED =========================
 *
 * Both programs are validated with bpf_validate() and EXECUTED with
 * bpf_filter() -- the interpreter the kernel itself uses -- against synthetic
 * frames AND against bytes captured from a real openssl handshake on FreeBSD.
 * See test/test_bpf_tls.c, which also runs the OLD fixed-offset program against
 * the same real bytes to show it rejects them.
 *
 * A filter that is never executed against known input is a guess. Both of the
 * versions this file replaces were guesses, and both were wrong.
 *
 * ============================== GENERATED CODE =============================
 *
 * The instruction tables below are generated by the script that accompanies
 * this port (genbpf.py), which simulates every branch and runs a local
 * interpreter over a matrix of frames before emitting anything. DO NOT
 * hand-edit the tables: re-run the generator with the header as its argument.
 * Jump offsets were hand-counted in the version that failed in production.
 *
 * NOTE ON LENGTH: bpf_filter() receives the captured length as its buflen, so a
 * load past the end of a short frame is rejected by the interpreter rather than
 * reading out of bounds. The length checks in the delivery program are about
 * IP-header arithmetic -- a malformed ip_total must not underflow into a
 * spurious accept -- not about buffer safety.
 */

#ifndef AETHER_SENSORD_BPF_TLS_H
#define AETHER_SENSORD_BPF_TLS_H

#include <stddef.h>

/*
 * Where the BPF definitions come from, per platform.
 *
 * FreeBSD: <net/bpf.h> is in base and has the struct and the opcode constants.
 * Linux: there is no <net/bpf.h> unless a kernel-uapi package is installed, but
 * <pcap/bpf.h> (libpcap-devel) carries the SAME classic-BPF definitions -- same
 * struct layout, same opcode names -- and it is also where bpf_filter() lives,
 * which the test uses. Using it keeps the program byte-identical on both
 * platforms, so a Linux developer can run the whole suite rather than only read
 * it. _DEFAULT_SOURCE is needed first because pcap/bpf.h uses the BSD typedefs
 * (u_int, u_char) that glibc does not declare by default.
 */
#if defined(__FreeBSD__)
#include <sys/types.h>
#include <sys/socket.h>
#include <net/bpf.h>
#else
#ifndef _DEFAULT_SOURCE
#define _DEFAULT_SOURCE 1
#endif
#include <sys/types.h>

#include <pcap/bpf.h>
#endif

/* Nonzero return = deliver the frame to userspace; 0 = drop. */
#define BPF_TLS_ACCEPT_ALL 0xffff

/*
 * Scratch memory used by bpf_tcp_payload. Scratch words are per-packet, so
 * there is no state to leak between frames.
 */
#define BPF_SCRATCH_TCP_BASE  0
#define BPF_SCRATCH_PAY_BASE  1
#define BPF_SCRATCH_IP_TOTAL  2
#define BPF_SCRATCH_L3_BASE   3
#define BPF_SCRATCH_HDR_BYTES 4

/*
 * Classifier: "does this packet START a TLS ClientHello?" -- in kernel, per
 * packet, cheap. Handles up to two VLAN tags and any IP/TCP header length.
 *
 * This is NOT the delivery gate: it cannot see a ClientHello that spans
 * segments. Use bpf_tcp_payload for delivery and let the reassembler decide.
 */
static const struct bpf_insn bpf_tls_clienthello[] = {
	{ BPF_LDX|BPF_W|BPF_IMM, 0, 0, 0xc },  /*  0: X = EtherType position (untagged) */
	{ BPF_LD|BPF_H|BPF_IND, 0, 0, 0x0 },  /*  1: A = EtherType */
	{ BPF_JMP|BPF_JEQ|BPF_K, 10, 0, 0x800 },  /*  2: IPv4? */
	{ BPF_JMP|BPF_JEQ|BPF_K, 1, 0, 0x8100 },  /*  3: 802.1Q tag? */
	{ BPF_JMP|BPF_JEQ|BPF_K, 0, 38, 0x88a8 },  /*  4: QinQ outer tag? */
	{ BPF_LDX|BPF_W|BPF_IMM, 0, 0, 0x10 },  /*  5: X = EtherType position after one tag */
	{ BPF_LD|BPF_H|BPF_IND, 0, 0, 0x0 },  /*  6: A = inner EtherType */
	{ BPF_JMP|BPF_JEQ|BPF_K, 5, 0, 0x800 },  /*  7: IPv4? */
	{ BPF_JMP|BPF_JEQ|BPF_K, 1, 0, 0x8100 },  /*  8: second tag? */
	{ BPF_JMP|BPF_JEQ|BPF_K, 0, 33, 0x88a8 },  /*  9: QinQ after one tag? */
	{ BPF_LDX|BPF_W|BPF_IMM, 0, 0, 0x14 },  /* 10: X = EtherType position after two tags */
	{ BPF_LD|BPF_H|BPF_IND, 0, 0, 0x0 },  /* 11: A = innermost EtherType */
	{ BPF_JMP|BPF_JEQ|BPF_K, 0, 30, 0x800 },  /* 12: IPv4? */
	{ BPF_MISC|BPF_TXA, 0, 0, 0x0 },  /* 13: A = EtherType position */
	{ BPF_ALU|BPF_ADD|BPF_K, 0, 0, 0x2 },  /* 14: +2 = L3 header base */
	{ BPF_MISC|BPF_TAX, 0, 0, 0x0 },  /* 15: X = L3 header base */
	{ BPF_MISC|BPF_TXA, 0, 0, 0x0 },  /* 16: A = L3 base (to stash it) */
	{ BPF_ST, 0, 0, 0x3 },  /* 17: M[3] = L3 base */
	{ BPF_LD|BPF_B|BPF_IND, 0, 0, 0x0 },  /* 18: A = version / IHL byte */
	{ BPF_ALU|BPF_AND|BPF_K, 0, 0, 0xf0 },  /* 19:  */
	{ BPF_JMP|BPF_JEQ|BPF_K, 0, 22, 0x40 },  /* 20: IPv4? */
	{ BPF_LDX|BPF_MEM, 0, 0, 0x3 },  /* 21: X = L3 base again */
	{ BPF_LD|BPF_B|BPF_IND, 0, 0, 0x9 },  /* 22: A = IP protocol */
	{ BPF_JMP|BPF_JEQ|BPF_K, 0, 19, 0x6 },  /* 23: TCP? */
	{ BPF_LD|BPF_H|BPF_IND, 0, 0, 0x6 },  /* 24: A = flags + fragment offset */
	{ BPF_JMP|BPF_JSET|BPF_K, 17, 0, 0x1fff },  /* 25: fragment? drop */
	{ BPF_LD|BPF_B|BPF_IND, 0, 0, 0x0 },  /* 26: A = version / IHL byte */
	{ BPF_ALU|BPF_AND|BPF_K, 0, 0, 0xf },  /* 27:  */
	{ BPF_ALU|BPF_MUL|BPF_K, 0, 0, 0x4 },  /* 28: IHL in bytes (honours IP options) */
	{ BPF_ALU|BPF_ADD|BPF_X, 0, 0, 0x0 },  /* 29: + L3 base = TCP header base */
	{ BPF_MISC|BPF_TAX, 0, 0, 0x0 },  /* 30: X = TCP header base */
	{ BPF_LD|BPF_B|BPF_IND, 0, 0, 0xc },  /* 31: A = TCP data-offset byte */
	{ BPF_ALU|BPF_AND|BPF_K, 0, 0, 0xf0 },  /* 32:  */
	{ BPF_ALU|BPF_RSH|BPF_K, 0, 0, 0x2 },  /* 33: TCP header length (honours TCP options) */
	{ BPF_ALU|BPF_ADD|BPF_X, 0, 0, 0x0 },  /* 34: + TCP base = TLS record base */
	{ BPF_MISC|BPF_TAX, 0, 0, 0x0 },  /* 35: X = payload base */
	{ BPF_LD|BPF_B|BPF_IND, 0, 0, 0x0 },  /* 36: A = TLS record content type */
	{ BPF_JMP|BPF_JEQ|BPF_K, 0, 5, 0x16 },  /* 37: handshake (0x16)? */
	{ BPF_LD|BPF_B|BPF_IND, 0, 0, 0x1 },  /* 38: A = TLS record major version */
	{ BPF_JMP|BPF_JEQ|BPF_K, 0, 3, 0x3 },  /* 39: TLS 1.x (0x03)? */
	{ BPF_LD|BPF_B|BPF_IND, 0, 0, 0x5 },  /* 40: A = handshake message type */
	{ BPF_JMP|BPF_JEQ|BPF_K, 0, 1, 0x1 },  /* 41: ClientHello (0x01)? */
	{ BPF_RET|BPF_K, 0, 0, 0xffff },  /* 42: ACCEPT */
	{ BPF_RET|BPF_K, 0, 0, 0x0 },  /* 43: DROP */
};

#define BPF_TLS_CLIENTHELLO_LEN 	((int)(sizeof bpf_tls_clienthello / sizeof bpf_tls_clienthello[0]))

/*
 * Delivery: "IPv4 + TCP + not a fragment + non-empty payload".
 *
 * Deliberately NOT the ClientHello pattern -- see the header comment. A
 * continuation segment of a large ClientHello looks like any other TCP payload,
 * and it must be delivered or the reassembler can never finish.
 */
static const struct bpf_insn bpf_tcp_payload[] = {
	{ BPF_LDX|BPF_W|BPF_IMM, 0, 0, 0xc },  /*  0: X = EtherType position (untagged) */
	{ BPF_LD|BPF_H|BPF_IND, 0, 0, 0x0 },  /*  1: A = EtherType */
	{ BPF_JMP|BPF_JEQ|BPF_K, 10, 0, 0x800 },  /*  2: IPv4? */
	{ BPF_JMP|BPF_JEQ|BPF_K, 1, 0, 0x8100 },  /*  3: 802.1Q tag? */
	{ BPF_JMP|BPF_JEQ|BPF_K, 0, 42, 0x88a8 },  /*  4: QinQ outer tag? */
	{ BPF_LDX|BPF_W|BPF_IMM, 0, 0, 0x10 },  /*  5: X = EtherType position after one tag */
	{ BPF_LD|BPF_H|BPF_IND, 0, 0, 0x0 },  /*  6: A = inner EtherType */
	{ BPF_JMP|BPF_JEQ|BPF_K, 5, 0, 0x800 },  /*  7: IPv4? */
	{ BPF_JMP|BPF_JEQ|BPF_K, 1, 0, 0x8100 },  /*  8: second tag? */
	{ BPF_JMP|BPF_JEQ|BPF_K, 0, 37, 0x88a8 },  /*  9: QinQ after one tag? */
	{ BPF_LDX|BPF_W|BPF_IMM, 0, 0, 0x14 },  /* 10: X = EtherType position after two tags */
	{ BPF_LD|BPF_H|BPF_IND, 0, 0, 0x0 },  /* 11: A = innermost EtherType */
	{ BPF_JMP|BPF_JEQ|BPF_K, 0, 34, 0x800 },  /* 12: IPv4? */
	{ BPF_MISC|BPF_TXA, 0, 0, 0x0 },  /* 13: A = EtherType position */
	{ BPF_ALU|BPF_ADD|BPF_K, 0, 0, 0x2 },  /* 14: +2 = L3 header base */
	{ BPF_MISC|BPF_TAX, 0, 0, 0x0 },  /* 15: X = L3 header base */
	{ BPF_MISC|BPF_TXA, 0, 0, 0x0 },  /* 16: A = L3 base (to stash it) */
	{ BPF_ST, 0, 0, 0x3 },  /* 17: M[3] = L3 base */
	{ BPF_LD|BPF_B|BPF_IND, 0, 0, 0x0 },  /* 18: A = version / IHL byte */
	{ BPF_ALU|BPF_AND|BPF_K, 0, 0, 0xf0 },  /* 19:  */
	{ BPF_JMP|BPF_JEQ|BPF_K, 0, 26, 0x40 },  /* 20: IPv4? */
	{ BPF_LD|BPF_B|BPF_IND, 0, 0, 0x9 },  /* 21: A = IP protocol */
	{ BPF_JMP|BPF_JEQ|BPF_K, 0, 24, 0x6 },  /* 22: TCP? */
	{ BPF_LD|BPF_H|BPF_IND, 0, 0, 0x6 },  /* 23: A = flags + fragment offset */
	{ BPF_JMP|BPF_JSET|BPF_K, 22, 0, 0x1fff },  /* 24: fragment? drop */
	{ BPF_LD|BPF_H|BPF_IND, 0, 0, 0x2 },  /* 25: A = IP total length */
	{ BPF_ST, 0, 0, 0x2 },  /* 26: M[2] = ip_total */
	{ BPF_LD|BPF_B|BPF_IND, 0, 0, 0x0 },  /* 27: A = version / IHL byte */
	{ BPF_ALU|BPF_AND|BPF_K, 0, 0, 0xf },  /* 28:  */
	{ BPF_ALU|BPF_MUL|BPF_K, 0, 0, 0x4 },  /* 29: IHL in bytes */
	{ BPF_ALU|BPF_ADD|BPF_X, 0, 0, 0x0 },  /* 30: + L3 base = TCP header base */
	{ BPF_MISC|BPF_TAX, 0, 0, 0x0 },  /* 31: X = TCP header base */
	{ BPF_LD|BPF_B|BPF_IND, 0, 0, 0xc },  /* 32: A = TCP data-offset byte */
	{ BPF_ALU|BPF_AND|BPF_K, 0, 0, 0xf0 },  /* 33:  */
	{ BPF_ALU|BPF_RSH|BPF_K, 0, 0, 0x2 },  /* 34: TCP header length */
	{ BPF_ALU|BPF_ADD|BPF_X, 0, 0, 0x0 },  /* 35: + TCP base = payload base */
	{ BPF_ST, 0, 0, 0x1 },  /* 36: M[1] = payload base */
	{ BPF_LD|BPF_MEM, 0, 0, 0x1 },  /* 37: A = payload base */
	{ BPF_LDX|BPF_MEM, 0, 0, 0x3 },  /* 38: X = L3 base */
	{ BPF_ALU|BPF_SUB|BPF_X, 0, 0, 0x0 },  /* 39: A = IP + TCP header bytes */
	{ BPF_ST, 0, 0, 0x4 },  /* 40: M[4] = header bytes */
	{ BPF_LD|BPF_MEM, 0, 0, 0x2 },  /* 41: A = ip_total */
	{ BPF_LDX|BPF_MEM, 0, 0, 0x4 },  /* 42: X = header bytes */
	{ BPF_ALU|BPF_SUB|BPF_X, 0, 0, 0x0 },  /* 43: A = payload length */
	{ BPF_JMP|BPF_JEQ|BPF_K, 2, 0, 0x0 },  /* 44: zero payload (pure ACK)? drop */
	{ BPF_JMP|BPF_JGT|BPF_K, 1, 0, 0xffff },  /* 45: underflow guard: ip_total < headers -> the subtraction wrapped; drop */
	{ BPF_RET|BPF_K, 0, 0, 0xffff },  /* 46: ACCEPT */
	{ BPF_RET|BPF_K, 0, 0, 0x0 },  /* 47: DROP */
};

#define BPF_TCP_PAYLOAD_LEN 	((int)(sizeof bpf_tcp_payload / sizeof bpf_tcp_payload[0]))

/*
 * Control program: accept everything.
 *
 * Required, not optional. An ng_bpf node with NO program installed drops every
 * frame, so "nothing arrived" cannot be read as a match decision unless the
 * graph has first been shown to deliver. Installing this is what makes a later
 * negative result meaningful.
 */
static const struct bpf_insn bpf_tls_accept_all[] = {
	{ BPF_LD|BPF_B|BPF_ABS, 0, 0, 0x0 },
	{ BPF_RET|BPF_K, 0, 0, 0xffff },
};

#define BPF_TLS_ACCEPT_ALL_LEN 	((int)(sizeof bpf_tls_accept_all / sizeof bpf_tls_accept_all[0]))

#endif /* AETHER_SENSORD_BPF_TLS_H */
